	<script src="assets/jquery-1.11.3-jquery.min.js"></script>
  <script src="assets/js/bootstrap.min.js"></script>
  <script src="../bower_components/angular/angular.js"></script>
  <script src="../client/app.js"></script>
  <script src="../bower_components/angular-cookies/angular-cookies.js"></script>
  <script src="../bower_components/angular-bootstrap/ui-bootstrap.js"></script>
  <script src="../bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
  <script src="../client/services.js"></script>
  <script src="../client/services/dbService.js"></script>
  <script src="../client/services/sessionService.js"></script>
  <script src="../client/services/utilityService.js"></script>
  <script src="../client/services/navCartService.js"></script>
  <script src="../client/controllers.js"></script>
  <script src="../client/controllers/homeController.js"></script>
  <script src="../client/controllers/navController.js"></script>
  <script src="../client/controllers/checkoutController.js"></script>
  <script src="../client/controllers/paymentFormController.js"></script>
  <script src="../client/controllers/orderConfirmationController.js"></script>
  <script src="../client/vanilla/domr.js" defer></script>
  <script src="../client/vanilla/vanillaCartManager.js" defer></script>
  <script src="../bower_components/angular-payments/lib/angular-payments.js"></script>
    